"use client"

import Link from "next/link"
import { PropertyCard } from "@/components/property-card"

export function TrendingProperties() {
  const trendingProperties = [
    {
      id: "prop1",
      images: ["/property-images/apartment-1.jpeg"],
      price: "€950",
      period: "/month",
      isPBSA: false,
      bills: "(bills included)",
      tags: ["Popular"],
      type: "Studio",
      size: "35 m²",
      bedrooms: "Studio",
      availableFrom: "Available from 15 Jun 2025",
      landlordType: "Private landlord",
      rating: 4.9,
      reviews: 28,
      depositInfo: "No Deposit",
      priceValue: 950,
      billsIncluded: true,
      title: "Modern Studio in City Center",
      location: "Amsterdam",
    },
    {
      id: "prop2",
      images: ["/property-images/apartment-2.jpeg"],
      price: "€1,250",
      period: "/month",
      isPBSA: false,
      bills: "(bills excluded)",
      tags: ["Luxury"],
      type: "Apartment",
      size: "75 m²",
      bedrooms: "2 bedrooms",
      bedroomCount: 2,
      availableFrom: "Available from 1 Jul 2025",
      landlordType: "Rental company",
      rating: 4.7,
      reviews: 42,
      priceValue: 1250,
      billsIncluded: false,
      title: "Spacious 2-Bedroom Apartment",
      location: "Barcelona",
    },
    {
      id: "prop3",
      images: ["/property-images/apartment-4.jpeg"],
      price: "€650",
      period: "/month",
      isPBSA: false,
      bills: "(bills included)",
      tags: ["New"],
      type: "Private room",
      size: "18 m²",
      availableFrom: "Available from 20 Jun 2025",
      landlordType: "Private landlord",
      rating: 4.8,
      reviews: 15,
      depositInfo: "Deposit Saver",
      priceValue: 650,
      billsIncluded: true,
      title: "Cozy Private Room in Shared Flat",
      location: "Berlin",
    },
    {
      id: "prop4",
      images: ["/property-images/apartment-5.jpeg"],
      price: "€1,800",
      period: "/month",
      isPBSA: false,
      bills: "(bills excluded)",
      tags: ["Luxury"],
      type: "Penthouse",
      size: "90 m²",
      bedrooms: "3 bedrooms",
      bedroomCount: 3,
      availableFrom: "Available from 10 Jul 2025",
      landlordType: "Rental company",
      rating: 4.9,
      reviews: 36,
      priceValue: 1800,
      billsIncluded: false,
      title: "Luxury Penthouse with Terrace",
      location: "Paris",
    },
    {
      id: "prop5",
      images: ["/property-images/apartment-6.jpeg"],
      price: "€850",
      period: "/month",
      isPBSA: false,
      bills: "(bills included)",
      tags: ["Pet friendly"],
      type: "Studio",
      size: "30 m²",
      bedrooms: "Studio",
      availableFrom: "Available from 5 Jul 2025",
      landlordType: "Private landlord",
      rating: 4.6,
      reviews: 19,
      depositInfo: "No Deposit",
      priceValue: 850,
      billsIncluded: true,
      title: "Pet-Friendly Studio Apartment",
      location: "Madrid",
    },
    {
      id: "prop6",
      images: ["/property-images/apartment-7.jpeg"],
      price: "€1,100",
      period: "/month",
      isPBSA: false,
      bills: "(bills excluded)",
      tags: ["New"],
      type: "Apartment",
      size: "60 m²",
      bedrooms: "1 bedroom",
      bedroomCount: 1,
      availableFrom: "Available from 12 Jul 2025",
      landlordType: "Rental company",
      rating: 4.7,
      reviews: 23,
      priceValue: 1100,
      billsIncluded: false,
      title: "Modern 1-Bedroom with Balcony",
      location: "London",
    },
    {
      id: "prop7",
      images: ["/property-images/apartment-8.jpeg"],
      price: "€750",
      period: "/month",
      isPBSA: false,
      bills: "(bills included)",
      tags: ["Student friendly"],
      type: "Private room",
      size: "22 m²",
      availableFrom: "Available from 25 Jun 2025",
      landlordType: "Private landlord",
      rating: 4.5,
      reviews: 31,
      depositInfo: "Deposit Saver",
      priceValue: 750,
      billsIncluded: true,
      title: "Student-Friendly Private Room",
      location: "Vienna",
    },
    {
      id: "prop8",
      images: ["/property-images/apartment-9.jpeg"],
      price: "€1,500",
      period: "/month",
      isPBSA: false,
      bills: "(bills excluded)",
      tags: ["Luxury"],
      type: "Loft",
      size: "85 m²",
      bedrooms: "2 bedrooms",
      bedroomCount: 2,
      availableFrom: "Available from 8 Jul 2025",
      landlordType: "Rental company",
      rating: 4.8,
      reviews: 27,
      priceValue: 1500,
      billsIncluded: false,
      title: "Industrial Loft in City Center",
      location: "Berlin",
    },
    {
      id: "prop9",
      images: ["/property-images/apartment-10.jpeg"],
      price: "€920",
      period: "/month",
      isPBSA: false,
      bills: "(bills included)",
      tags: ["Popular"],
      type: "Studio",
      size: "38 m²",
      bedrooms: "Studio",
      availableFrom: "Available from 18 Jun 2025",
      landlordType: "Private landlord",
      rating: 4.9,
      reviews: 34,
      depositInfo: "No Deposit",
      priceValue: 920,
      billsIncluded: true,
      title: "Bright Studio with City View",
      location: "Prague",
    },
    {
      id: "prop10",
      images: ["/property-images/apartment-11.jpeg"],
      price: "€1,350",
      period: "/month",
      isPBSA: false,
      bills: "(bills excluded)",
      tags: ["New"],
      type: "Apartment",
      size: "70 m²",
      bedrooms: "2 bedrooms",
      bedroomCount: 2,
      availableFrom: "Available from 3 Jul 2025",
      landlordType: "Rental company",
      rating: 4.6,
      reviews: 18,
      priceValue: 1350,
      billsIncluded: false,
      title: "Newly Renovated 2-Bedroom",
      location: "Amsterdam",
    },
    {
      id: "prop11",
      images: ["/property-images/apartment-12.jpeg"],
      price: "€680",
      period: "/month",
      isPBSA: false,
      bills: "(bills included)",
      tags: ["Student friendly"],
      type: "Private room",
      size: "20 m²",
      availableFrom: "Available from 22 Jun 2025",
      landlordType: "Private landlord",
      rating: 4.7,
      reviews: 25,
      depositInfo: "Deposit Saver",
      priceValue: 680,
      billsIncluded: true,
      title: "Cozy Room Near University",
      location: "Barcelona",
    },
    {
      id: "prop12",
      images: ["/property-images/apartment-13.jpeg"],
      price: "€1,650",
      period: "/month",
      isPBSA: false,
      bills: "(bills excluded)",
      tags: ["Luxury"],
      type: "Apartment",
      size: "95 m²",
      bedrooms: "3 bedrooms",
      bedroomCount: 3,
      availableFrom: "Available from 15 Jul 2025",
      landlordType: "Rental company",
      rating: 4.9,
      reviews: 32,
      priceValue: 1650,
      billsIncluded: false,
      title: "Luxury 3-Bedroom with Terrace",
      location: "Paris",
    },
  ]

  return (
    <div className="py-8">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-bold">Trending now</h2>
        <Link href="/search" className="text-[#FF4B27] font-medium hover:underline">
          View all
        </Link>
      </div>
      <div className="flex gap-6 overflow-x-auto pb-4 no-scrollbar">
        {trendingProperties.map((property) => (
          <div key={property.id} className="flex-shrink-0 w-[300px]">
            <PropertyCard {...property} />
          </div>
        ))}
      </div>
    </div>
  )
}
